### PR TITLE
Execute gradle clean when add/remove plugin

### PR DESCRIPTION
**Pull request by Fatme**
Temporary fix for this issue https://github.com/NativeScript/android-runtime/issues/230

### CODE REVIEW

**Comment by slavchev** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by Fatme** [comment]
This PR should be merged for 1.5 release

**Comment by teobugslayer** [comment]
This PR is under consideration. We are discussing our options with Android runtime developers and may not need to merge it.

**Comment by Fatme** [comment]
Android runtime will improve metadata generator so we don't this anymore.

**Pull request closed without merging**
