### PR TITLE
null/undefined check added

### PR DESCRIPTION
**Pull request by enchev**
Related to #https://github.com/NativeScript/nativescript-cli/issues/1734

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
In case cocoadpodVer is null/undefined, the following line will fail as well:
https://github.com/NativeScript/nativescript-cli/pull/1804/files#diff-054de9ebd89900812d117a4a095f7e5fR53
Can you add the check there as well:
```TypeScript
let shouldUseXcproj = cocoapodVer && !!(semver.lt(cocoapodVer, "1.0.0") && ~helpers.versionCompare(xcodeVersion, "7.3.0")),
```

**Comment by vakrilov** [comment]
💯

**Comment by hshristov** [comment]
I though we cannot install CLI if there is no CocoaPod installed. Right?

**Comment by rosen-vladimirov** [comment]
@hshristov 
Cocoapods are not mandatory (or at least by 2.0.1 they have not been mandatory for NativeScript CLI).

**Comment by rosen-vladimirov** [comment]
:+1: after green build

**Comment by hshristov** [comment]
👍

**Pull request merged**
