### PR TITLE
I tried my best to make your readme a little better. I think it looks nice : )

### PR DESCRIPTION
**Pull request by KartSriv**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [x] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by KartSriv** [comment]
@cla-bot check

**Comment by miroslavaivanova** [comment]
run ci

**Comment by miroslavaivanova** [comment]
run ci

**Comment by miroslavaivanova** [comment]
run ci

**Comment by KartSriv** [comment]
It's been 14 days and no information about PR.

**Comment by Fatme** [comment]
@KartSriv,

Thank you for your contribution and sorry for the delayed response.

**Pull request merged**
