### PR TITLE
perf: use prompts instead of inquirer

### PR DESCRIPTION
**Pull request by janoshrubos**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the current behavior?

Using inquirer package

## What is the new behavior?

Using prompts package instead of inquirer in the prompter.

### CODE REVIEW

**Comment by NathanaelA** [comment]
I don't know anything about `inquirer` or `prompts` package (so I guess I need to go look them up). But if the existing `inquirer` package is working; why swap it, what is the use case for swaping something that has been working for a couple years to a different untested package?

**Comment by janoshrubos** [comment]
Yes, @rigor789 had the idea to replace the packages to reduce the size of the cli.

**Comment by rigor789** [comment]
Yep the goal was to reduce the CLI size!

```
Before (7.0.11):
239 369 798 bytes (286,7 MB on disk) for 17 350 items

After (this PR):
233 977 884 bytes (268,9 MB on disk) for 13 576 items

Diff:
-17,8 MB on disk
-3774 files
```

I think that's a decent reduction from a relatively small change! 

/cc @NathanaelA @NathanWalker

**Review by NathanaelA — APPROVED** [review]
Looking at the code, I see nothing wrong and reducing the CLI dependencies is a good thing.    Thanks!

LGTM...

**Review by rigor789 — APPROVED** [review]

**Pull request merged**
