### PR TITLE
[fix]: provide appId to webpack config

### PR DESCRIPTION
**Pull request by farfromrefug**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Review by NathanWalker — APPROVED** [review]

**Comment by vallemar** [comment]
any documentation on this?

**Comment by farfromrefug** [comment]
@vallemar dont think so that part of the CLI is not really documented

**Comment by vallemar** [comment]
@farfromrefug  true, I thought that was here https://docs.nativescript.org/configuration/webpack

**Comment by rigor789** [comment]
They should be documented here:

image

Will add once we publish this.

**Comment by vallemar** [comment]
@rigor789 When I saw that I thought that it could only be passed as a parameter in the terminal, can we add something quick that indicates that those flags can be passed through webpack and a simple example of one???

**Comment by rigor789** [comment]
@vallemar these are internal flags, you wouldn't normally pass them via the terminal unless you're doing something completely out of the ordinary - like running webpack separately on it's own or whatever. The CLI passes these automatically based on nativescript config, and are then used by webpack config to set `__ANDROID__` and so globals, enable/disable hmr etc.

**Pull request merged**
