### PR TITLE
Add support for Node 4.1.x+

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Add support for Node 4.1.x+ by updating our dependencies.

https://github.com/NativeScript/nativescript-cli/issues/958

### CODE REVIEW

**Comment by dtopuzov** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by teobugslayer** [comment]
:+1:

**Comment by cime** [comment]
@rosen-vladimirov any reason why this will be ready only for 1.5 and not 1.4 which should be released this month?

**Pull request merged**
