### PR TITLE
Document --bundle

### PR DESCRIPTION
**Pull request by Mitko-Kerezov**
In addition, update submodule reference to latest master.

Part of https://github.com/NativeScript/NativeScript/issues/5129

Ping @PanayotCankov @dtopuzov @MartoYankov

### CODE REVIEW

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
Closing this, will introduce documentation in https://github.com/NativeScript/nativescript-cli/pull/3246

**Pull request closed without merging**
