### PR TITLE
XML validation fixed

### PR DESCRIPTION
**Pull request by enchev**
Related to #1777

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
Maybe you should update this test as it expects to return false when there's invalid `.xml`, but with current changes the code will throw error
https://github.com/NativeScript/nativescript-cli/blob/master/test/platform-service.ts#L340

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
@rosen-vladimirov done!

**Comment by rosen-vladimirov** [comment]
:+1:

**Pull request merged**
