### PR TITLE
feat(logs): support sourcemaps from `.map` files

### PR DESCRIPTION
**Pull request by farfromrefug**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by rigor789** [comment]
@farfromrefug possible to add a test case in `test/services/log-source-map-service.ts`? Haven't looked extensively at it, but if needed we can create temp files like we do in some of the tests.

**Comment by farfromrefug** [comment]
Sure can try. Going to take me a bit of time though.thanks

**Comment by farfromrefug** [comment]
@rigor789 actually not that eady to create a test for this (doable though) because it depends on external files. Don't really have the time to do it :s sorry. 
Could you test the change on your side and release? 
Really needs  this. And a consequence of that could be that all source maps could be external. Would be very practical on sims and also much faster! 
Thanks

**Review by rigor789 — APPROVED** [review]
Added test cases now, LGTM

**Pull request merged**
