### PR TITLE
This PR add pnpm full support

### PR DESCRIPTION
**Pull request by farfromrefug**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [x] Tests for the changes are included.

## What is the new behavior?
you can choose pnpm as the package manager

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug ,
Thanks a lot for the contribution. Can you please fix the linting error, so we can run some tests. Currently building of the package fails with:
```
ERROR: /home/travis/build/NativeScript/nativescript-cli/lib/package-manager.ts:104:9 - missing whitespace
```

**Comment by farfromrefug** [comment]
@rosen-vladimirov done. BTW for now i use ```--shamefully-hoist``` option for pnpm. We get to much errors without it. Might change that in the future if i manage to fix it.

**Comment by rosen-vladimirov** [comment]
test cli-smoke cli-templates

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug ,
I've tested your PR locally and it works awesome, great work! The only thing I've noticed is the command `tns plugin remove <plugin name>` fails with error. For example, in my case:
```
tns plugin remove nativescript-ui-listview
Command failed: pnpm remove nativescript-ui-listview --save
 ERROR  Unknown option 'save'
```
Can you please take a look at this issue? After that we can merge this PR.

**Comment by farfromrefug** [comment]
My bad! Will fix it this morning.

**Comment by rosen-vladimirov** [comment]
Hey @farfromrefug ,
Did you have a chance to take a look at the issue? If you want, I can try to take a look at it and push a fix

**Comment by rosen-vladimirov** [comment]
test cli-smoke

**Comment by rosen-vladimirov** [comment]
This PR implements https://github.com/NativeScript/nativescript-cli/issues/4654

**Pull request merged**
