### PR TITLE
Fixes "Error:Error: ENOENT, readdir '/private/var/lib/jenkins/workspace/tns-stable-build-testapps-android-full/TestApp/app/tns_modules'"

### PR DESCRIPTION
**Pull request by Fatme**

### CODE REVIEW

**Comment by dtopuzov** [comment]
:+1:

**Comment by teobugslayer** [comment]
Will this change work with existing,  old projects?

**Comment by Fatme** [comment]
I've fixed the code to work properly with old projects.

**Comment by teobugslayer** [comment]
Excellent,  :+1:

**Pull request merged**
