### PR TITLE
feat: add sample test in TypeScript for ts projects on test init command

### PR DESCRIPTION
**Pull request by Fatme**
https://github.com/NativeScript/nativescript-cli/issues/1798

## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by Fatme** [comment]
test cli-tests

**Comment by Fatme** [comment]
test cli-tests

**Comment by Fatme** [comment]
test cli-tests

**Comment by dtopuzov** [comment]
test cli-tests package_version#latest

**Comment by Fatme** [comment]
test cli-tests package_version#latest

**Comment by Fatme** [comment]
test cli-tests

**Comment by Fatme** [comment]
test cli-tests

**Comment by Fatme** [comment]
test cli-tests nativescript-dev-typescript#latest

**Comment by Fatme** [comment]
test cli-tests package#latest

**Comment by Fatme** [comment]
test cli-tests package#next

**Comment by Fatme** [comment]
test cli-tests package#next

**Comment by Fatme** [comment]
test cli-tests

**Comment by Fatme** [comment]
test cli-tests package_version#latest

**Comment by Fatme** [comment]
test cli-tests nativescript-unit-test-runner#next nativescript-dev-typescript#latest

**Comment by Fatme** [comment]
test cli-tests package_version#next

**Comment by Fatme** [comment]
test cli-tests nativescript-dev-webpack#next

**Comment by Fatme** [comment]
test cli-tests nativescript-dev-webpack#next nativescript-dev-typescript#next

**Comment by Fatme** [comment]
test cli-tests nativescript-dev-webpack#next nativescript-angular#next

**Comment by Fatme** [comment]
test cli-tests nativescript-dev-webpack#next

**Comment by DimitarTachev** [comment]
test cli-tests nativescript-dev-webpack#next

**Comment by Fatme** [comment]
test cli-tests nativescript-dev-webpack#next

**Comment by miroslavaivanova** [comment]
test cli-tests nativescript-dev-webpack#next nativescript-angular#rc tns-core-modules#rc tns-ios#rc tns-android#rc nativescript-dev-typescript#rc

**Comment by Fatme** [comment]
test cli-tests nativescript-dev-webpack#rc

**Pull request merged**
