### PR TITLE
Revert "Restart app upon debugging"

### PR DESCRIPTION
**Pull request by Mitko-Kerezov**
This reverts commit 5b1141c1bcc8362acce97d2b69422de19959942e.
In case a second debug attempt fails just throw the error.

Ping @rosen-vladimirov @TsvetanMilanov

### CODE REVIEW

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Pull request merged**
