### PR TITLE
Remove plugins that are not supported for platform

### PR DESCRIPTION
**Pull request by TsvetanMilanov**
When copying the plugins to the platform specific tns_modules folder the plugins that are not supported for the specified platform should be removed.

### CODE REVIEW

**Comment by TsvetanMilanov** [comment]
run ci

**Comment by TsvetanMilanov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by TsvetanMilanov** [comment]
run ci

**Comment by TsvetanMilanov** [comment]
Closed because when platform specific plugin is required when the app is used in not supported platform it will throw an error and this will break many old projects.

**Pull request closed without merging**
