### PR TITLE
Update build-tools to 25.0.2 in setup scripts

### PR DESCRIPTION
**Pull request by vchimev**

### CODE REVIEW

**Comment by vchimev** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
Can you explain why this change is required?

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
@rosen-vladimirov, It is a consequence of https://github.com/NativeScript/android-runtime/commit/3a92285af04a626b8fc4ad4534ac0d0a1d5acff7.

**Comment by vchimev** [comment]
run ci

**Comment by vchimev** [comment]
@rosen-vladimirov,
It's already in there: https://github.com/NativeScript/nativescript-cli/commits/release.
This PR contains cherry-picked commits from the release branch.

**Pull request merged**
