### PR TITLE
feat: compute and log build time

### LINKED ISSUE #2998: Doesn't show time taken to build for ios
`tns build android` shows time time taken to complete build but `tns build ios` doesn't

### PR DESCRIPTION
**Pull request by amaaniqbal**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the current behavior?
Build time not shown in ios.

## What is the new behavior?
Build time is computed and logged irrespective of OS.

Fixes/Implements/Closes #2998.

### CODE REVIEW

**Review by rigor789 — APPROVED** [review]

**Comment by edusperoni** [comment]
this throws `performance is not defined` on our CI build

**Comment by rigor789** [comment]
@edusperoni good to know, we can use a different time source I guess, or a polyfill.

It is strange however, because according to the node docs, `performance.now` has been available since node 8.5

https://nodejs.org/api/perf_hooks.html#performancenow

Do you have more context around the error? Can you try running the CI build with `--log trace`?

**Comment by edusperoni** [comment]
Yes, that fix solves it. I was just testing it locally and  `import { performance } from "perf_hooks";` is required for it to work on node.

**Comment by rigor789** [comment]
@edusperoni I tested the above and worked on my end without the import, using node v15.11.0. 😕

**Pull request merged**
