### PR TITLE
add --inspector flag to tns options

### PR DESCRIPTION
**Pull request by Pip3r4o**
fixes #3200

### CODE REVIEW

**Comment by Pip3r4o** [comment]
run ci

**Comment by Pip3r4o** [comment]
@Mitko-Kerezov I'll rebase to master before pushing, thanks!

**Comment by Pip3r4o** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Pull request merged**
