### PR TITLE
Update lodash to 4.13.1

### PR DESCRIPTION
**Pull request by TsvetanMilanov**
The lodash.d.ts is now for version 4.0.0 but for our usage it is OK.
From the lodash changelog (https://github.com/lodash/lodash/wiki/Changelog) you can see that from version 4.0.0 to version 4.13.1 there are no breacking changes.

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
ping @ErjanGavalji , @enchev

**Comment by enchev** [comment]
:+1:

**Comment by tzraikov** [comment]
👍

**Pull request merged**
