### PR TITLE
fix: incorrect error for non-supported Node.js version

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
In case you are using unsupported Node.js version CLI must show you error that this version is not supported and to inform you which is the supported range. Currently this is not working and CLI shows error for `Unexpected token`.
The problem is that CLI has some specific logic to check the Node.js version and the code should be pure ES5 syntax in order to work with old Node.js versions (by default CLI's code is ES6).
The current issue is caused by using string interpolation in the mentioned code. Fix the message to fix the problem.

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes https://github.com/NativeScript/nativescript-cli/issues/4665

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
test cli-smoke

**Comment by rosen-vladimirov** [comment]
test cli-smoke nativescript-dev-typescript#latest

**Comment by dtopuzov** [comment]
test cli-smoke nativescript-dev-typescript#latest tns-core-modules#5.4.0

**Comment by rosen-vladimirov** [comment]
test cli-smoke nativescript-dev-typescript#latest tns-core-modules#5.4.0

**Comment by rosen-vladimirov** [comment]
test cli-smoke nativescript-dev-typescript#latest tns-core-modules#5.4.0

**Comment by rosen-vladimirov** [comment]
test cli-smoke nativescript-dev-typescript#latest tns-core-modules#5.4.0

**Comment by rosen-vladimirov** [comment]
test cli-smoke

**Pull request merged**
