### PR TITLE
fix: fix the activity regex in order to match activities with capital letters

### PR DESCRIPTION
**Pull request by DimitarTachev**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [x] Tests for the changes are included.

## What is the current behavior?
We cannot start applications with a custom activity containing capital letters in their package names.

## What is the new behavior?
We can start those applications.

Related to #3818

### CODE REVIEW

**Comment by DimitarTachev** [comment]
run ci

**Comment by Fatme** [comment]
run ci

**Comment by RoyiNamir** [comment]
@DimitarTachev @Fatme @tsonevn 
Hi.

I saw the fix with the new regex. . But still there is a subtle warning here.
You've fixed the capital matching  in the REPEATING parts to be `[a-zA-Z]` - but you left the rule that the immediate NEXT LETTER should be capital.

In other words you still enforce this : `*.*.[capital]*`
The enforcement : 

image



You can see it here : 

Full match : 

image

but if I change `.M` to `.m` then no match : 

image


if it was delibirate , then fine. but if it wasnt  , it should be changed.

**Comment by DimitarTachev** [comment]
Hi @RoyiNamir,

Thanks for pointing into that. By convention, all Java classes should start with a capital letter. That's the reason for having this part of the regex just after the last dot. Its matching the activity class name.

**Pull request merged**
