### PR TITLE
Ignore .DS_Store file changes on Mac

### PR DESCRIPTION
**Pull request by roblav96**
### chokidar#path-filtering
https://github.com/paulmillr/chokidar#path-filtering

Resolves:
https://github.com/NativeScript/nativescript-cli/issues/2472

### CODE REVIEW

**Comment by roblav96** [comment]
Ye nevermind this didn't resolve the issue :X

**Comment by rosen-vladimirov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run CI

**Comment by dtopuzov** [comment]
run CI

**Comment by dtopuzov** [comment]
run CI

**Comment by dtopuzov** [comment]
run CI

**Pull request merged**
