### PR TITLE
fix(build): Speedup iOS build

### PR DESCRIPTION
**Pull request by Fatme**
Remove the unneeded `xcodebuild` command that CLI executes when building iOS projects

### CODE REVIEW

**Comment by dtopuzov** [comment]
run ci

**Comment by Fatme** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
run ci

**Comment by dtopuzov** [comment]
Tests are green :)

**Pull request merged**
