### PR TITLE
Update submodule reference

### PR DESCRIPTION
**Pull request by Mitko-Kerezov**
On some systems with slower hard drives and rigorous antivirus software, on numerous occasions the newly created files in `platforms` directory are locked and cannot be renamed. The rename of platform specific files (e.g. `app.android.ts` to `app.ts`) fails with `EPERM`.
Switching to write+delete in favor of rename eliminates said issue.

Ping @rosen-vladimirov @KristianDD

### CODE REVIEW

**Comment by Mitko-Kerezov** [comment]
Merging this as the failing test is due to changes in the android template text messages

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by Mitko-Kerezov** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
Closing as the submodule had already been updated.

**Pull request closed without merging**
