### PR TITLE
Update readme.md - Remove android-17 from android update sdk script.

### PR DESCRIPTION
**Pull request by vchimev**

### CODE REVIEW

**Comment by Fatme** [comment]
:+1:

**Comment by dtopuzov** [comment]
:+1:

**Comment by rosen-vladimirov** [comment]
:-1:

**Comment by vchimev** [comment]
@rosen-vladimirov - Done, thanks.

**Comment by rosen-vladimirov** [comment]
great work, thanks for fixing this 
:+1: :+1: 
:100:

**Pull request merged**
