### PR TITLE
Update dependencies in order to fix minimatch warning

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
As some of the dependencies are using old version of minimatch, the following warning appears during installation of nativescript CLI:
`npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

Update some of the dependencies in order to stop showing the warning. However it is still there as the broccoli dependency is not updated for more than 8 months and it depends on old version of glob module.
Same is valid for the node-inspector version that we are using and that we cannot upgrade at the moment.

Partial fix for: https://github.com/NativeScript/nativescript-cli/issues/1948

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
ping @enchev , @dtopuzov , @vchimev , @pkoleva

**Comment by dtopuzov** [comment]
:+1:

**Comment by vchimev** [comment]
👍

**Comment by fatenhealy** [comment]
I am getting the same warning:
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Thanks,
Faten

**Pull request merged**
