### PR TITLE
Fixed a path not found issue where the variable was not being wrapped in quotes

### PR DESCRIPTION
**Pull request by NickBranstein**
Fixed a path not found issue where the variable was not being wrapped
in quotes

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
Hi @NickBranstein 
We've tried your fix on our side, but it looks like the quotes do not work for us. The original code works even when there's space in the directory name. May I ask you for more details on your case, steps to reproduce the unexpected behavior will be a great help for us.
Also what's your OS version and PowerShell version?

**Comment by NickBranstein** [comment]
Thanks @rosen-vladimirov - I'm running Windows 10 x64. Powershell version 5.

When I ran the following from (which runs the install script), everything works until the end where I get Path not found errors.

`start-process -FilePath PowerShell.exe -Verb Runas -Wait -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/NativeScript/nativescript-cli/production/setup/native-script.ps1'))"`

Strangely enough I tried this on several other Windows 10 machines with the same problem. I also had to manually fix my ANDROID_HOME and JAVA_HOME variables because the script had pointed them to the wrong spot (different problem but not sure what is causing that).

Seems like after I fixed those variables and I am rerunning the script today I no longer need to add the parens. After a little more investigation I think this is because it somehow found the wrong path. I ran this on a new VM i spun up on Azure and it had another version of the JDK already installed in C:\Program Files (x86)\Java - I'm going to try and uninstall the versions and give the script a shot again. Sorry for any confusion!

**Comment by NickBranstein** [comment]
No such luck still fails for me. Perhaps this should be an issue now because I think this fix won't appear to work in all cases. Here is the error I get on a new Windows 10x64 install. Powershell version 5.

error

**Comment by Mitko-Kerezov** [comment]
@NickBranstein
We can't seem to reproduce the issue on our side - tried it in. According to [ss64](http://ss64.com/ps/syntax-operators.html) parentheses are used for grouping expressions only. Meaning that `"$androidExecutable"` will expand the variable and the result will be the variable's value, while `"($androidExecutable)"` results in the variable's value inside parentheses.

You said your `ANDROID_HOME` and `JAVA_HOME` variables were wrong - could you tell us what their values were?

My guess is that you had an `android` executable, but it was not added to your `PATH` environment variable. In this case, the script defaults to `"$env:localappdata\Android\android-sdk"`

**Comment by NickBranstein** [comment]
`ANDROID_HOME` did point to the default user profile location.
`JAVA_HOME` pointed to an older version of the java framework in `c:\program files (x86)\java\` 

Strangely enough the android sdk was installed but it was installed to `c:\program files\android\` (which is where I had to update the path to.

**Comment by Mitko-Kerezov** [comment]
Looks like the following happened:
 1. You installed the android sdk `c:\program files\android\` but didn't add `c:\program files\android\tools` in your `PATH` environment variable.
 2. The script detected you didn't have the `ANDROID_HOME` environment variable set and tried to set it for you.
  1. The script tries to locate the android sdk but fails because it hasn't been added to the `PATH` (hence, it can't be executed unless a full path is provided) in which case it defaults to `"$env:localappdata\Android\android-sdk"`
  2. Your `ANDROID_HOME` environment variable is set to `"$env:localappdata\Android\android-sdk"`

Then later on when the script tries to run the executable `android`, using the `ANDROID_HOME` variable it fails because the variable's value is plain wrong.

The proper fix for this problem (and all other related future problems) would be to verify that the `android` executable can be run and that it is where `ANDROID_HOME` says it is.

If that seems reasonable to you I'll address it in a separate pull request and we can close this one?

**Comment by NickBranstein** [comment]
Yes I think it should be a separate pull request thanks. I think the fix is to verify the location of the android executable properly and create the variable like you said.  Thanks!

**Pull request closed without merging**
