### PR TITLE
fix: update ns-dev-xcode to fix extension framework removal

### PR DESCRIPTION
**Pull request by KristianDD**
## PR Checklist

- [ ] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [ ] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [ ] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/nativescript-cli/blob/master/CONTRIBUTING.md#contribute-to-the-code-base
- [ ] Tests for the changes are included.

## What is the new behavior?

Fixes/Implements/Closes #[Issue Number].

### CODE REVIEW

**Comment by KristianDD** [comment]
test cli-smoke cli-templates

**Comment by dtopuzov** [comment]
test cli-smoke cli-templates nativescript-dev-typescript#next

**Comment by dtopuzov** [comment]
test cli-smoke cli-templates nativescript-dev-typescript#latest

**Comment by rosen-vladimirov** [comment]
Merging as current failures are caused by tns-core-modules' rc version.

**Pull request merged**
