### PR TITLE
Deprecate iOS deployment target check for frameworks

### PR DESCRIPTION
**Pull request by jasssonpet**
NativeScript for iOS 2.1 has a minimum one of 8.0.

ping @ivanbuhov

### CODE REVIEW

**Comment by ivanbuhov** [comment]
Why not remove the whole deployment target check? The only reason I can think of is to support old runtime/project template version with the latest CLI, but is this something we need to support?

**Comment by jasssonpet** [comment]
I think it's best to deprecate it now and remove it in a future release. This way we will not break currently existing applications.

**Comment by jasssonpet** [comment]
run ci

**Comment by jasssonpet** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Pull request merged**
