### PR TITLE
Remove library add command

### PR DESCRIPTION
**Pull request by teobugslayer**
See https://github.com/NativeScript/nativescript-cli/issues/1239

### CODE REVIEW

**Comment by dtopuzov** [comment]
:+1:

**Comment by vchimev** [comment]
Why not first implement `plugin init` to facilitate the transition from adding native libraries by `library add` to adding them by `plugin add`?

**Comment by ikoevska** [comment]
:+1: for the docs part

**Comment by teobugslayer** [comment]
run ci

**Comment by rosen-vladimirov** [comment]
:+1:

**Pull request merged**
