### PR TITLE
Fixed: test command fails with exception

### PR DESCRIPTION
**Pull request by tzraikov**
The stack trace: 

`TypeError: Cannot read property 'ios' of undefined
    at FiberFuture.Future.wait (/Users/raikov/work/nativescript-cli/node_modules/fibers/future.js:566:15)
    at fiberBootstrap.run (/Users/raikov/work/nativescript-cli/lib/services/test-execution-service.ts:133:36)
    at fiber (/Users/raikov/work/nativescript-cli/lib/common/fiber-bootstrap.ts:10:3)
    - - - - -
    at <anonymous> (/Users/raikov/work/nativescript-cli/lib/services/test-execution-service.ts:239:104)
    at Function.settle (/Users/raikov/work/nativescript-cli/node_modules/fibers/future.js:249:26)
    at FiberFuture.Future.wait (/Users/raikov/work/nativescript-cli/node_modules/fibers/future.js:565:10)
    at fiberBootstrap.run (/Users/raikov/work/nativescript-cli/lib/services/test-execution-service.ts:133:36)
    at fiber (/Users/raikov/work/nativescript-cli/lib/common/fiber-bootstrap.ts:10:3)`

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
Call stack is from `master` branch ( I see `__awaiter` in it, which is available when using Promises). Does the issue reproduce in the `release` branch as well (call stack will be different)

**Comment by tzraikov** [comment]
Yes, the isssue is reproduced in release branch and the fix is relevant both in master and release.

**Comment by tzraikov** [comment]
Updated the stacktrace from release

**Comment by tzraikov** [comment]
run ci

**Pull request merged**
