### PR TITLE
Update requirement for Android Build Tools

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Set minimum required Android Build Tools 23.0.0

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
ping @Plamen5kov @teobugslayer @dtopuzov @vchimev

**Comment by Plamen5kov** [comment]
:+1:

**Comment by vchimev** [comment]
@rosen-vladimirov, we should update also the docs.

**Comment by rosen-vladimirov** [comment]
@vchimev  I know, I'll do this in a separate PR in the docs repo :)

**Pull request merged**
